version: '3.3'
services:

  post_db:
    image: mongo:${db_version}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db
          - post_db

  ui:
    env_file:
      - .env
    image: ${username}/ui:${ui_version}
    ports:
      - ${port}:${port}/tcp
    networks:
      - front_net

  post:
    env_file:
      - .env
    image: ${username}/post:${post_version}
    networks:
      back_net:
        aliases:
          - post
      front_net:
        aliases:
          - post

  comment:
    env_file:
      - .env
    image: ${username}/comment:${comment_version}
    networks:
      back_net:
        aliases:
          - comment
      front_net:
        aliases:
          - comment

  prometheus:
    env_file:
      - .env
    image: ${username}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    networks:
      back_net:
      front_net:
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    networks:
      back_net:
      front_net:

    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

  
volumes:
  post_db:
  prometheus_data:


networks:
  front_net:
    ipam:
      config:
        - subnet: ${front_net_range}
  back_net:
    ipam:
      config:
        - subnet: ${back_net_range}

